#! /bin/sh
username='kali'
wmname LG3D &
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
feh --bg-fill $HOME/Desktop/$username/images/fondoPantalla.jpg
bspc config focus_follows_pointer true
picom --experimental-backend &
bspc config border_width 1.5
$HOME/.config/polybar/launch.sh